name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"   # cada día 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write   # ✅ permite commitear el SVG al repo
  

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Liliana99
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Madrid

          # Lenguajes (muy útil para frontend)
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

          # Repos destacados
          plugin_repositories: no
          plugin_repositories_featured: no
          plugin_repositories_pinned: 6

          # Actividad / hábitos
          plugin_habits: no
          plugin_habits_facts: yes
          plugin_habits_charts: no
